### ISSUE TITLE
Latches not processed

### ISSUE THREAD

**Issue by Abd-Bin** [rafaelcalcada/aigbdd#1]
Hi,

I am getting this error:
This graph contains latches. The current version of this implementation do not support them.

As per my understanding AIG format includes latches. 

thanks!

**Comment by riscv-steel** [comment]
Hi,

The implementation indeed does not support latches and therefore sequential circuits. I'm updating the README page to make it clear for future users.

Thanks for pointing this out.

Rafael.

**Comment by rafaelcalcada** [comment]
Hi,

The implementation indeed does not support latches and therefore sequential circuits. I'm updating the README page to make it clear for future users.

Thanks for pointing this out.

Rafael.

**Comment by rafaelcalcada** [comment]
Hi,

The implementation indeed does not support latches and therefore sequential circuits. I'm updating the README page to make it clear for future users.

Thanks for pointing this out.

Rafael.
